quarkus.banner.enabled=false
quarkus.log.level=SEVERE
quarkus.log.category.kube-kport.level=INFO
quarkus.log.console.format=[🌀k8s-kport] %s%e%n
quarkus.native.additional-build-args=-H:ReflectionConfigurationFiles=reflection-config.json,--initialize-at-run-time=org.eclipse.jkube.kit.common.util.IoUtil,--initialize-at-run-time=org.apache.sshd.common.random,--initialize-at-run-time=org.fusesource.jansi,-H:DeadlockWatchdogInterval=30
quarkus.native.resources.includes=consoleui_messages.properties,META-INF/jkube/remote-dev.properties,org/fusesource/jansi/internal/native/Windows/x86_64/jansi.dll,org/fusesource/jansi/internal/native/Windows/x86/jansi.dll
quarkus.package.jar.add-runner-suffix=false
quarkus.package.output-name=kubectl-kport
