quarkus.banner.enabled=false
quarkus.log.level=SEVERE
quarkus.log.category.kube-kport.level=INFO
quarkus.log.console.format=[🌀k8s-kport] %s%e%n
quarkus.native.additional-build-args=-H:ReflectionConfigurationFiles=reflection-config.json,-H:JNIConfigurationFiles=jni-config.json,--initialize-at-run-time=org.eclipse.jkube.kit.common.util.IoUtil,--initialize-at-run-time=org.apache.sshd.common.random,--initialize-at-run-time=org.fusesource.jansi,-H:DeadlockWatchdogInterval=30
quarkus.native.resources.includes=consoleui_messages.properties,META-INF/jkube/remote-dev.properties,META-INF/native/windows64/jansi.dll,META-INF/native/windows32/jansi.dll
quarkus.package.jar.add-runner-suffix=false
quarkus.package.output-name=kubectl-kport
