quarkus.native.additional-build-args=--initialize-at-run-time=org.eclipse.jkube.kit.common.util.IoUtil,--initialize-at-run-time=org.apache.sshd.common.random,--initialize-at-run-time=org.fusesource.jansi.internal
quarkus.native.resources.includes=META-INF/jkube/remote-dev.properties
quarkus.http.port=10680
quarkus.package.jar.add-runner-suffix=false
quarkus.package.output-name=kport-ide-server
