name: "[PR] Build native binaries"
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  build:
    name: Build kubectl-kport and kport-ide-server native binaries on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest,windows-latest,ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          path: kport

      - uses: actions/checkout@v4
        with:
          repository: quarkiverse/quarkus-sshd
          path: quarkus-sshd

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm-community'
          github-token: ${{ github.token }}
          native-image-job-reports: 'false'

      - name: Build quarkus-sshd (SNAPSHOT)
        working-directory: quarkus-sshd
        run: |
          mvn install -DskipTests

      - name: Build All on ${{ matrix.os }}
        working-directory: kport
        run: |
          mvn clean install -DskipTests -Dnative

      - name: Upload kubectl for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: kubectl-kport-${{ runner.os }}.exe
          path: kport/kubectl-kport/target/kubectl-kport.exe
          retention-days: 1

      - name: Upload kport-ide-server for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: kport-ide-server-${{ runner.os }}.exe
          path: kport/kport-ide-server/target/kport-ide-server.exe
          retention-days: 1

      - name: Upload kubectl
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: kubectl-kport-${{ runner.os }}
          path: kport/kubectl-kport/target/kubectl-kport
          retention-days: 1

      - name: Upload kport-ide-server
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: kport-ide-server-${{ runner.os }}
          path: kport/kport-ide-server/target/kport-ide-server
          retention-days: 1

