name: "[PR] Build JVM on Linux"
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  build:
    name: Build on Linux (JVM)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          path: kport

      - uses: actions/checkout@v4
        with:
          repository: quarkiverse/quarkus-sshd
          path: quarkus-sshd

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build quarkus-sshd (SNAPSHOT)
        working-directory: quarkus-sshd
        run: |
          mvn install -DskipTests

      - name: Build All (JVM)
        working-directory: kport
        run: |
          mvn clean install -DskipTests
