name: "[RELEASE] Build native binaries"
on:
  release:
    types: [published]
jobs:
  build:
    name: Build kubectl-kport and kport-ide-server native binaries on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest,windows-latest,ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          path: kport

      - uses: actions/checkout@v4
        with:
          repository: quarkiverse/quarkus-sshd
          path: quarkus-sshd

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm-community'
          github-token: ${{ github.token }}
          native-image-job-reports: 'false'

      - name: Build quarkus-sshd (SNAPSHOT)
        working-directory: quarkus-sshd
        run: |
          mvn install -DskipTests

      - name: Build All on ${{ matrix.os }}
        working-directory: kport
        run: |
          mvn clean install -DskipTests -Dnative

      - name: Upload kubectl for Windows
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: kport/kubectl-kport/target/kubectl-kport.exe#kubectl-kport-${{ runner.os }}.exe

      - name: Upload kport-ide-server for Windows
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: kport/kport-ide-server/target/kport-ide-server.exe#kport-ide-server-${{ runner.os }}.exe
      
      - name: Upload kubectl
        if: matrix.os != 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: kport/kubectl-kport/target/kubectl-kport#kubectl-kport-${{ runner.os }}

      - name: Upload kport-ide-server
        if: matrix.os != 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: kport/kport-ide-server/target/kport-ide-server#kport-ide-server-${{ runner.os }}

